# Generated by Django 4.2.19 on 2025-02-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_news_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='book_type',
            field=models.CharField(choices=[('📖 Бумага', 'Текстовая'), ('📱Текст', 'Электронная'), ('🎧Аудио', 'Аудио')], default='📖 Бумага', max_length=20),
        ),
    ]
