# Generated by Django 4.2.19 on 2025-02-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sliderimage_alter_news_title_delete_likedislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(default='Без названия', max_length=255),
        ),
    ]
