# Generated by Django 4.2.19 on 2025-02-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_news_image_alter_sliderimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='Неизвестный автор', max_length=100),
        ),
    ]
