# Generated by Django 4.2.19 on 2025-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_news_image_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='book_type',
            field=models.CharField(choices=[('text', 'Текстовая'), ('ebook', 'Электронная'), ('audio', 'Аудио')], default='text', max_length=10),
        ),
    ]
