# Generated by Django 4.2.19 on 2025-02-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_news_is_published_alter_news_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='book_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='book_type',
            field=models.CharField(choices=[('📖 Бумага', 'Бумажная книга'), ('📱Текст', 'Электронная книга'), ('🎧Аудио', 'Аудиокнига')], default='📖 Бумага', max_length=20),
        ),
    ]
