# Generated by Django 4.2.19 on 2025-02-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_news_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='reader',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(),
        ),
    ]
